export enum DAY_WEEK {
	MONDAY = 1,
	TUESDAY = 2,
	WEDNESDAY = 3,
	THURSDAY = 4,
	FRIDAY = 5,
	SATURDAY = 6,
	SUNDAY = 0,
}

export enum TYPE_REPEAT {
	NONE = 0,
	DAILY = 1,
	WEEKLY = 2,
	MONTHLY = 3,
	ANNUALLY = 4,
}

export enum DAY_MONTH {
	Last = 'last',
	One = '1',
	Two = '2',
	Three = '3',
	Four = '4',
	Five = '5',
	Six = '6',
	Seven = '7',
	Eight = '8',
	Nine = '9',
	Ten = '10',
	Eleven = '11',
	Twelve = '12',
	Thirteen = '13',
	Fourteen = '14',
	Fifteen = '15',
	Sixteen = '16',
	Seventeen = '17',
	Eighteen = '18',
	Nineteen = '19',
	Twenty = '20',
	TwentyONe = '21',
	TwentyTwo = '22',
	TwentyThree = '23',
	TwentyFour = '24',
	TwentyFive = '25',
	TwentySix = '26',
	TwentySeven = '27',
	TwentyEight = '28',
	TwentyNine = '29',
	Thirty = '30',
	ThirtyOne = '31',
}
